services:
  postgres:
    image: postgres:16-alpine
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: me
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - shareit_pgdata:/var/lib/postgresql/data

volumes:
  shareit_pgdata:
